
:scrollbar:
:data-uri:
:noaudio:
== Lab Scenario

Financial Services company FinTech provides back-end services for their clients in the Financial Services industry. Unfortunately a widespread global attack on Cisco Routers has disrupted their network infrastructure and broken a key customer facing application.

Your role, as a *Red Hat Ansible Networking Consultant*, is to regain control of the network infrastructure, restore network services, and protect against further attacks. FinTech have provided Red Hat with an outline of key steps for this engagement.

* Access the current state of the Networking Infrastructure
** Explore the existing level of connectivity and router configuration
* Preserve for InfoSec as forensics the current configurations of the routers
** Backup both routers current configurations
* Re-establish connectivity between the 2 FinTech Data Centers
** Setup a networking tunnel between the 2 sites (GRE)
** Restore routing between the 2 sites
* Test the application now works as expected
** Can the application front-end now access the remote data center hosting the
application?


ifdef::showscript[]
Transcript:

This lab draws heavily on the Ansible Linklight Networking Lab with a fun
security twist to it and some extra steps.

Each of you will have your own environment which you will explore and then
gradually re-configure until you have gained complete control of the
environment. So lets take a look...

endif::showscript[]



