
:scrollbar:
:data-uri:
:noaudio:
== Ansible Device Connectivity: `ansible_network_os`

* Both `network_cli` and `NETCONF` require you to specify the `ansible_network_os`
** Informs Ansible what type of platform network device conforms to
** `ansible_network_os` vendor specific e.g. `eos`, `ios`, `junos` etc
[source,ini]
----
[arista]
eos ansible_host=192.168.2.10 ansible_connection=network_cli ansible_network_os=eos

[juniper]
junos ansible_host=192.168.2.20 ansible_connection=netconf ansible_network_os=junos
----

.Table Title
|===
|Network Platform|`ansible_network_os`

|Arista EOS
|eos

|Cisco IOS
|ios

|Cisco IOS-XR
|iosxr

|Cisco NX-OS
|nxos

|Juniper Junos
|junos

|VyOS
|vyos
|===

ifdef::showscript[]
Transcript:

Both `NETCONF` and `network_cli` need information about the devices they are
connecting to and this is supplied by the inventory variable
`ansible_network_os`.

In todays lab you will be setting this to `ios` and using `network_cli` to
connect to the Cisco routers. However Ansible provides support for the
major network operating systems for example Arista's EOS, Juniper's junos etc..

endif::showscript[]




