
:scrollbar:
:data-uri:
:noaudio:
== Ansible Networking Modules

- Ansible has extensive support with hundreds of modules for Networking
- Broad support for a wide variety of vendors and devices

However *3 Core groups of Modules* provide *extensive* capability

* `*_facts` e.g. `ios_facts`, `eos_facts`, `junos_facts` etc
** Perform same fact gathering function as `setup` module for servers

* `*_command` e.g. `ios_command`, `eos_command`, `junos_command` etc
** Similar to `command` module
** Allows Network Operators to talk to devices using familiar syntax

+
[source,bash]
----
$ ansible cisco -m ios_command -a "commands='sh banner motd'" -c network_cli
----

* `*_config` e.g. `ios_config`, `eos_config`, `junos_config` etc
** Allows Network Operators to configure devices using:
*** Familiar syntax
*** Configuration Files

ifdef::showscript[]
=== Transcript

Whilst Ansible has hundreds of modules available for Networking Devices
increasingly the direction is converging around 3 core groups of modules.

The first group are the `*_facts` modules which can be prefixed by the network
operating system, for example today we will use `ios_facts` to explore the
routers. These modules perform a similar function to the `setup` module which
does not support networking devices. So it is typical to see `gather_facts:` set
to `false` in Networking Playbooks

Next are the `*_command` modules. These allow Network Operators to execute
commands against network devices. What is particularly powerful is once an
operator learns the simple syntax around the module the commands that are sent
are exactly the same as the commands an operator would type on the console of
the device.

Finally the 3rd group of modules are the `*_config` modules for configuring
Network Devices. Again they leverage the same command sets and operators can
include both commands and load configuration or backup files onto the target
devices.

endif::showscript[]





